# -*- coding: utf-8 -*-
"""Assignment 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OFYebvt0CYlc8grkqAKIXJk5h-r0DS8W
"""

from google.colab import drive
drive.mount('/content/drive')

import os
directory = "/content/drive/MyDrive/CSE422 lab 4"
os.chdir(directory)

import pandas as pd
df = pd.read_csv('wine.csv')
df

df.shape
df.columns
df.head()
df.sample()

df.isnull().sum()

df.info()

df['quality'].unique()

df['quality'] = df['quality'].map({'good':1, 'bad':0})
print(df[['quality']].head())

from sklearn.preprocessing import MinMaxScaler
scaling = []
for i in df:
  mx = max(df[i])
  mn = min(df[i])
  if mn<0 or mx>1:
    scaling.append(i)

scaler = MinMaxScaler()
for i in scaling:
  scaler.fit(df[[i]])
  df[i] = scaler.transform(df[[i]])

for_cor=df.corr()
import seaborn as sns
sns.heatmap(for_cor, cmap="cool")

drp = ['fixed acidity', 'total sulfur dioxide']
df = df.drop(drp,axis=1)

from sklearn.model_selection import train_test_split
list_of_features=[]
for i in df:
  if i!="quality":
    list_of_features.append(i)
print(list_of_features)
x_data =  df[list_of_features]
y_data =  df['quality']
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,test_size=0.2,random_state=1)